# Default configuration for signstream RVQ training

data:
  root: /workspace/data/public_data/CSL_Daily
  split: train
  fps: 25
  chunk_len: 10
  augment:
    mirror: true
    time_warp: true
    dropout_prob: 0.05

model:
  latent_dim: 256
  type_embed_dim: 16
  rvq:
    levels: 2
    codebook_size: 128
    commitment_beta: 0.25

train:
  epochs: 1
  batch_size: 2
  lr: 1e-3
  wd: 0.0
  device: cpu
  seed: 42

export:
  enable_rle: true
  rle_threshold: 0.02
